bind -n S-Left  previous-window
bind -n S-Right next-window

set -g pane-border-status top
set -g pane-border-format "#{pane_title}"

set -g mouse on
setw -g mode-keys vi
set -g copy-command 'pbcopy'
